<?php
/**
 * Player display page view
 * 
 * @version $Id: show.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

require_once 'Zend/Controller/Front.php';

// Render common HTML header
echo $this->render('partials/html_header.phtml');

// Render the common page headers
//echo $this->render('partials/player_list.phtml');

?>

	<h2>Player List: <?= $this->escape($this->deptname); ?></h2>
<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php else: ?>
<?php if (! empty($this->players)): ?>
	<table class="player_list">
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Steam ID</th>
			<th>Overall Level</th>
			<th>Crystals</th>
			<th>Vespene</th>
		</tr>
<?php foreach ($this->players as $player): ?>
		<tr>
			<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/player/show/ident/' . urlencode($player->player_ident) ?>"><?= 
				htmlspecialchars($player->player_ident) ?></a></td>
			<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/player/show/pname/' . urlencode($player->name) ?>"><?= 
				htmlspecialchars($player->name) ?></a></td>
			<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/player/show/steamid/' . urlencode($player->steamid) ?>"><?= 
				htmlspecialchars($player->steamid) ?></a></td>
			<td><?= $this->escape($player->overall_level) ?></td>
			<td><?= $this->escape($player->crystals) ?></td>
			<td><?= $this->escape($player->vespene) ?></td>
		</tr>
<?php endforeach; ?>
	</table>
<?php else: ?>
	No player has been selected.
<?php endif; ?>

<?php endif; ?>

<?= $this->render('partials/html_footer.phtml'); ?>
